apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: neoforge
  labels:
    app.kubernetes.io/name: neoforge-app-config
    app.kubernetes.io/instance: neoforge-app-config
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: neoforge
data:
  # Environment configuration
  ENVIRONMENT: "production"
  DEBUG: "false"

  # API Configuration
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  API_BASE_URL: "https://api.neoforge.example.com"
  FRONTEND_URL: "https://neoforge.example.com"

  # CORS Configuration
  CORS_ORIGINS: '["https://neoforge.example.com", "https://www.neoforge.example.com", "https://staging.neoforge.example.com"]'
  CORS_CREDENTIALS: "true"
  CORS_METHODS: '["GET", "POST", "PUT", "DELETE", "OPTIONS"]'
  CORS_HEADERS: '["*"]'

  # Database Configuration (non-sensitive)
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "neoforge"
  DB_POOL_SIZE: "20"
  DB_MAX_OVERFLOW: "30"
  DB_POOL_TIMEOUT: "30"
  DB_POOL_RECYCLE: "3600"

  # Redis Configuration (non-sensitive)
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_MAX_CONNECTIONS: "50"
  REDIS_TIMEOUT: "5"
  REDIS_RETRY_ON_TIMEOUT: "true"

  # Celery Configuration
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/1"
  CELERY_TASK_SERIALIZER: "json"
  CELERY_RESULT_SERIALIZER: "json"
  CELERY_ACCEPT_CONTENT: '["json"]'
  CELERY_TIMEZONE: "UTC"
  CELERY_ENABLE_UTC: "true"
  CELERY_TASK_ALWAYS_EAGER: "false"
  CELERY_TASK_EAGER_PROPAGATES: "true"
  CELERY_WORKER_CONCURRENCY: "2"
  CELERY_WORKER_MAX_TASKS_PER_CHILD: "1000"
  CELERY_TASK_TIME_LIMIT: "300"
  CELERY_TASK_SOFT_TIME_LIMIT: "240"

  # Email Configuration (non-sensitive)
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "neoforge@example.com"
  SMTP_USE_TLS: "true"
  SMTP_USE_SSL: "false"
  EMAIL_FROM: "NeoForge <neoforge@example.com>"
  EMAIL_TEMPLATES_DIR: "/app/email_templates"

  # JWT Configuration (non-sensitive)
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "30"

  # Security Configuration
  BCRYPT_ROUNDS: "12"
  PASSWORD_MIN_LENGTH: "8"
  SESSION_TIMEOUT: "3600"
  MAX_LOGIN_ATTEMPTS: "5"
  LOGIN_ATTEMPT_TIMEOUT: "900"

  # Rate Limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS: "100"
  RATE_LIMIT_WINDOW: "60"
  RATE_LIMIT_STORAGE_URL: "redis://redis:6379/2"

  # Logging Configuration
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  LOG_FILE: "/app/logs/app.log"
  LOG_MAX_SIZE: "100MB"
  LOG_BACKUP_COUNT: "5"

  # Monitoring Configuration
  METRICS_ENABLED: "true"
  METRICS_PORT: "8000"
  METRICS_PATH: "/metrics"
  HEALTH_CHECK_PATH: "/health"
  READY_CHECK_PATH: "/health/ready"

  # Application Configuration
  APP_NAME: "NeoForge"
  APP_VERSION: "1.0.0"
  APP_DESCRIPTION: "A modern full-stack starter kit"
  DOCS_URL: "/docs"
  REDOC_URL: "/redoc"
  OPENAPI_URL: "/openapi.json"

  # Feature Flags
  ENABLE_REGISTRATION: "true"
  ENABLE_EMAIL_VERIFICATION: "true"
  ENABLE_PASSWORD_RESET: "true"
  ENABLE_SOCIAL_LOGIN: "false"
  ENABLE_2FA: "false"
  ENABLE_AUDIT_LOGGING: "true"

  # Cache Configuration
  CACHE_TTL: "3600"
  CACHE_PREFIX: "neoforge:"
  CACHE_MAX_CONNECTIONS: "50"

  # File Upload Configuration
  UPLOAD_MAX_SIZE: "10485760"  # 10MB
  UPLOAD_ALLOWED_EXTENSIONS: '["jpg", "jpeg", "png", "gif", "pdf", "doc", "docx"]'
  UPLOAD_PATH: "/app/uploads"

  # Pagination Configuration
  DEFAULT_PAGE_SIZE: "20"
  MAX_PAGE_SIZE: "100"

  # Timezone Configuration
  TIMEZONE: "UTC"
  DEFAULT_LOCALE: "en_US"
  SUPPORTED_LOCALES: '["en_US", "es_ES", "fr_FR", "de_DE"]'

  # Development and Testing
  TESTING: "false"
  PYTEST_WORKERS: "auto"

  # Performance Configuration
  WORKER_PROCESSES: "1"
  WORKER_CONNECTIONS: "1000"
  WORKER_TIMEOUT: "30"
  KEEPALIVE: "2"
  MAX_REQUESTS: "1000"
  MAX_REQUESTS_JITTER: "100"

  # Database Migration Configuration
  ALEMBIC_CONFIG: "/app/alembic.ini"
  AUTO_MIGRATE: "false"  # Set to true only for development

  # External Services Configuration
  EXTERNAL_API_TIMEOUT: "30"
  EXTERNAL_API_RETRIES: "3"
  EXTERNAL_API_BACKOFF_FACTOR: "0.3"
