apiVersion: v1
kind: Service
metadata:
  name: neoforge-backend
  namespace: neoforge
  labels:
    app: neoforge-backend
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: neoforge-backend
    component: api