apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: neoforge
  labels:
    app: frontend
    component: web
    app.kubernetes.io/name: neoforge-frontend
    app.kubernetes.io/instance: neoforge-frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: neoforge
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
    prometheus.io/path: "/metrics"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 9113
    targetPort: 9113
    protocol: TCP
    name: metrics
  selector:
    app: frontend
    component: web
  sessionAffinity: None