apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: neoforge
  labels:
    app: postgres
    component: database
type: Opaque
data:
  # Base64 encoded values - replace with actual values in production
  # echo -n 'your-actual-password' | base64
  POSTGRES_USER: cG9zdGdyZXM= # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXNfcHJvZF9wYXNzd29yZF8yMDI1 # postgres_prod_password_2025
  POSTGRES_DB: bmVvZm9yZ2U= # neoforge
  POSTGRES_REPLICATION_USER: cmVwbGljYXRvcg== # replicator
  POSTGRES_REPLICATION_PASSWORD: cmVwbGljYXRvcl9wYXNzd29yZF8yMDI1 # replicator_password_2025
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-backup-secret
  namespace: neoforge
  labels:
    app: postgres
    component: backup
type: Opaque
data:
  # S3 or cloud storage credentials for backups
  # Replace with actual cloud storage credentials
  AWS_ACCESS_KEY_ID: eW91cl9hd3NfYWNjZXNzX2tleQ== # your_aws_access_key
  AWS_SECRET_ACCESS_KEY: eW91cl9hd3Nfc2VjcmV0X2FjY2Vzc19rZXk= # your_aws_secret_access_key
  BACKUP_ENCRYPTION_KEY: YmFja3VwX2VuY3J5cHRpb25fa2V5XzIwMjU= # backup_encryption_key_2025
