apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: neoforge
  labels:
    app: postgres
    component: database
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  - port: 9187
    targetPort: 9187
    protocol: TCP
    name: metrics
  selector:
    app: postgres
    component: database
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: neoforge
  labels:
    app: postgres
    component: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres
    component: database
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-read
  namespace: neoforge
  labels:
    app: postgres
    component: database
    service-type: read-replica
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres
    component: database
    role: replica  # For future read replicas