apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: neoforge
  labels:
    app: redis
    component: cache-secret
    app.kubernetes.io/name: redis-secret
    app.kubernetes.io/instance: neoforge-redis-secret
    app.kubernetes.io/component: cache-secret
    app.kubernetes.io/part-of: neoforge
type: Opaque
data:
  # Base64 encoded Redis password - change in production
  # echo -n "your_redis_password_here" | base64
  # Default: "redis-prod-password-2024" (change this!)
  REDIS_PASSWORD: cmVkaXMtcHJvZC1wYXNzd29yZC0yMDI0
---
# Separate secret for Redis configuration that requires password
apiVersion: v1
kind: Secret
metadata:
  name: redis-auth-config
  namespace: neoforge
  labels:
    app: redis
    component: cache-auth
    app.kubernetes.io/name: redis-auth-config
    app.kubernetes.io/instance: neoforge-redis-auth
    app.kubernetes.io/component: cache-auth
    app.kubernetes.io/part-of: neoforge
type: Opaque
stringData:
  redis-auth.conf: |
    # Authentication configuration
    requirepass redis-prod-password-2024
    
    # ACL (Access Control List) Configuration
    # Create users with specific permissions
    user default on >redis-prod-password-2024 ~* &* -@dangerous +@all
    user celery on >celery-worker-pass ~celery* +@all -@dangerous
    user api on >api-service-pass ~cache* ~session* +@read +@write +@stream -@dangerous
    
    # Rename dangerous commands
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    rename-command KEYS ""
    rename-command CONFIG "CONFIG_b4d7a8c9f2e1"
    rename-command DEBUG ""
    rename-command EVAL "EVAL_secure_a1b2c3"
    rename-command SCRIPT ""