"""Test example endpoints."""
import pytest
from typing import Dict
from httpx import AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import text

from app.core.cache import clear_cache
from app.core.config import get_settings, Settings
from app.models.user import User
from tests.factories import UserFactory

pytestmark = pytest.mark.asyncio


@pytest.fixture
async def test_user(db: AsyncSession) -> User:
    """Create a test user for authentication."""
    user = await UserFactory.create(session=db, email="test-example@example.com")
    await db.commit()
    return user


@pytest.fixture
async def test_user_headers(test_user: User, test_settings: Settings) -> Dict[str, str]:
    """Get headers for test user authentication."""
    from app.core.security import create_access_token
    from datetime import timedelta
    
    access_token_expires = timedelta(minutes=test_settings.access_token_expire_minutes)
    access_token = create_access_token(
        subject=str(test_user.id),
        settings=test_settings,
        expires_delta=access_token_expires
    )
    return {
        "Authorization": f"Bearer {access_token}",
        "Accept": "application/json",
        "Content-Type": "application/json",
        "User-Agent": "TestClient",
    }


async def test_cached_users(client: AsyncClient, db: AsyncSession, test_settings: Settings):
    """Test cached users endpoint."""
    # Clear existing data
    await db.execute(text("DELETE FROM users WHERE email LIKE '%cachedtest%'"))
    await clear_cache() # Clear Redis cache
    
    # Create test users
    test_users = []
    test_user_emails = set()
    for i in range(3):
        email = f"cachedtest{i}@example.com"
        user = await UserFactory.create(
            session=db,
            email=email
            # Other necessary fields will be generated by the factory
        )
        test_users.append(user)
        test_user_emails.add(email)
    # Commit after creating all users to ensure visibility for the API call
    
    # Headers for non-authenticated endpoint
    headers = {
        "Accept": "application/json",
        "User-Agent": "TestClient"
    }
    
    # First request should hit database
    response = await client.get(f"{test_settings.api_v1_str}/examples/cached-users", headers=headers)
    assert response.status_code == 200
    users_from_api = response.json()
    api_user_emails = {user['email'] for user in users_from_api}
    assert test_user_emails.issubset(api_user_emails) # Verify our users are present

    # Second request should hit cache
    response2 = await client.get(f"{test_settings.api_v1_str}/examples/cached-users", headers=headers)
    assert response2.status_code == 200
    users_from_api2 = response2.json()
    assert len(users_from_api2) == len(users_from_api) # Check if same number of users returned

    # Verify cache hit (requires instrumentation or specific cache headers)
    # E.g., check for a hypothetical 'X-Cache-Hit' header
    # assert response2.headers.get('X-Cache-Hit') == 'true'


async def test_query_types(client: AsyncClient, test_settings: Settings):
    """Test query types endpoint."""
    headers = {
        "Accept": "application/json",
        "User-Agent": "TestClient"
    }
    response = await client.get(f"{test_settings.api_v1_str}/examples/query-types", headers=headers)
    assert response.status_code == 200
    data = response.json()
    assert "query_timings" in data
    timings = data["query_timings"]
    assert "select" in timings
    assert "join" in timings
    assert "transaction" in timings
    # Example assertion: check if select took at least 50ms due to pg_sleep
    assert float(timings["select"]["duration"]) >= 0.05 


async def test_connection_pool(client: AsyncClient, test_settings: Settings):
    """Test connection pool endpoint."""
    headers = {
        "Accept": "application/json",
        "User-Agent": "TestClient"
    }
    response = await client.get(f"{test_settings.api_v1_str}/examples/connection-pool", headers=headers)
    assert response.status_code == 200
    data = response.json()
    assert "pool_stats" in data
    assert isinstance(data["pool_stats"], dict)


async def test_error_handling(client: AsyncClient, test_settings: Settings):
    """Test error handling endpoint."""
    headers = {
        "Accept": "application/json",
        "User-Agent": "TestClient"
    }
    response = await client.get(f"{test_settings.api_v1_str}/examples/error-handling", headers=headers)
    assert response.status_code == 500 # Expecting Internal Server Error
    data = response.json()
    assert "detail" in data
    # Check for a specific error message if applicable, otherwise just the presence of detail
    assert data["detail"] == "Query error demonstration"