"""Test example endpoints."""
import pytest
from typing import Dict
from httpx import AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import text

from app.core.cache import clear_cache
from app.core.config import get_settings, Settings
from app.models.user import User
from tests.factories import UserFactory

pytestmark = pytest.mark.asyncio


@pytest.fixture
async def test_user(db: AsyncSession) -> User:
    """Create a test user for authentication."""
    user = await UserFactory.create(session=db, email="test-example@example.com")
    await db.commit()
    return user


@pytest.fixture
async def test_user_headers(test_user: User, test_settings: Settings) -> Dict[str, str]:
    """Get headers for test user authentication."""
    from app.core.security import create_access_token
    from datetime import timedelta
    
    access_token_expires = timedelta(minutes=test_settings.access_token_expire_minutes)
    access_token = create_access_token(
        subject=str(test_user.id),
        settings=test_settings,
        expires_delta=access_token_expires
    )
    return {
        "Authorization": f"Bearer {access_token}",
        "Accept": "application/json",
        "Content-Type": "application/json",
        "User-Agent": "TestClient",
    }


async def test_cached_users(client: AsyncClient, db: AsyncSession, test_settings: Settings):
    """Test cached users endpoint."""
    # Clear existing data
    await db.execute(text("DELETE FROM users WHERE email LIKE '%cachedtest%'"))
    await db.commit()
    await clear_cache() # Clear Redis cache
    
    # Create test users manually to avoid passing invalid kwargs
    test_users = []
    for i in range(3):
        user = await UserFactory.create(
            session=db,
            email=f"cachedtest{i}@example.com"
            # Other necessary fields will be generated by the factory
        )
        test_users.append(user)
    # Commit after creating all users if create doesn't commit automatically
    # await db.commit() # Removed as UserFactory.create handles commit
    
    # Headers for non-authenticated endpoint
    headers = {
        "Accept": "application/json",
        "User-Agent": "TestClient"
    }
    
    # First request should hit database
    response = await client.get(f"{test_settings.api_v1_str}/examples/cached-users", headers=headers)
    assert response.status_code == 200
    assert len(response.json()) == 3
    # Check cache headers/logic if implemented
    
    # Second request should use cache
    response = await client.get(f"{test_settings.api_v1_str}/examples/cached-users", headers=headers)
    assert response.status_code == 200
    assert len(response.json()) == 3
    # Verify cache hit if possible (e.g., check logs or metrics if available)
    
    # Clear cache and verify it hits database again
    await clear_cache()
    response = await client.get(f"{test_settings.api_v1_str}/examples/cached-users", headers=headers)
    assert response.status_code == 200
    assert len(response.json()) == 3


async def test_query_types(client: AsyncClient, test_settings: Settings):
    """Test query types endpoint."""
    headers = {
        "Accept": "application/json",
        "User-Agent": "TestClient"
    }
    response = await client.get(f"{test_settings.api_v1_str}/examples/query-types", headers=headers)
    assert response.status_code == 200
    data = response.json()
    assert "query_timings" in data
    timings = data["query_timings"]
    assert "select" in timings
    assert "join" in timings
    assert "transaction" in timings
    # Example assertion: check if select took at least 50ms due to pg_sleep
    assert float(timings["select"]["duration"]) >= 0.05 


async def test_connection_pool(client: AsyncClient, test_settings: Settings):
    """Test connection pool endpoint."""
    headers = {
        "Accept": "application/json",
        "User-Agent": "TestClient"
    }
    response = await client.get(f"{test_settings.api_v1_str}/examples/connection-pool", headers=headers)
    assert response.status_code == 200
    data = response.json()
    assert "pool_stats" in data
    assert isinstance(data["pool_stats"], dict)


async def test_error_handling(client: AsyncClient, test_settings: Settings):
    """Test error handling endpoint."""
    headers = {
        "Accept": "application/json",
        "User-Agent": "TestClient"
    }
    response = await client.get(f"{test_settings.api_v1_str}/examples/error-handling", headers=headers)
    assert response.status_code == 500 # Expecting Internal Server Error
    data = response.json()
    assert "detail" in data
    # Check for a specific error message if applicable, otherwise just the presence of detail
    assert data["detail"] == "Query error demonstration"